### ISSUE TITLE
Laravel 官方的 Elixir 有了较大变化

### ISSUE THREAD

**Issue by zhuzhichao** [laravel-china/docs#41]
Laravel 官方的 Elixir 有了较大变化，特别是资源的路径，原来 from resources/css 变为 resources/assets/css 了，对应的 js 目录也变了。今天遇到这样的问题，因为 elixir 版本升级了，导致出现执行 gulp 报错的问题。 谁有时间能把这个给更新一下？

**Comment by lifesign** [comment]
今晚合并更新

**Comment by zhuzhichao** [comment]
@lifesign  Love you ！ :rose:

**Comment by nauxliu** [comment]
@lifesign Love you :rose:

**Comment by lifesign** [comment]
已合并

**Comment by summerblue** [comment]
已更新.
