### ISSUE TITLE
共同翻译 Laravel 5.1 文档

### ISSUE THREAD

**Issue by artiship** [laravel-china/docs#42]
https://github.com/laravel/docs/pull/1623

**Comment by lifesign** [comment]
近期我们会开始，主要是5.1刚发布不久， Taylor 也在不停的更新，即使现在翻译了文档 ，势必遇到重复翻译的问题，而且 laravel-china 所维护的文档也不希望是 “一次性” 的。从 4.2 以及 5.0 的 commit 你也可以看到，我们是定期 merge 官方仓库的。 这周末在 phphub 上 我们会发起一个帖子来邀请大家一起协作，欢迎加入，感谢你的热心和付出！

**Comment by artiship** [comment]
因为翻译也需要校对审查，也不是一次性的，所以才可以一边翻译一边合并官网最新的修改提交，而不会受影响整体，况且 laravel/docs 的修改都是非常小的改动，包括一些语法和措辞的问题，5.1 既已正式发布，也说明文档基本完成，接受的只是修改与补充，不影响翻译。

在 5.1 刚发布不久我就开始了翻译的工作，然后又将翻译搬到了 Github 上，目前已经初步完成了许多章节，https://github.com/laragirl/docs, 在翻译的过程中我也及时对原分支的新提交作了多次合并

我以为翻译是件极花时间的事情，大家都有自己的工作要做，做这些事情也无报酬，所以我希望大家可以一起来做这件事情，包括台湾正做翻译的伙伴们，我也跟他们提过这个想法 https://github.com/laravel-taiwan/docs/issues/178   希望大家可以一起做这件事情，避免无必要的重复。

至于翻译，我可以尽我所能提供支持

**Comment by lifesign** [comment]
我们在做 laravel 翻译的时候，是以 laravel-china 这个组织来作为发布的，这样才能更长久的去做好一件事，所以一直没有用个人的账号去做。不知道您是否愿意提交 PR 给 laravel-china 我们合并之后共同翻译？

台湾同胞那边的翻译，之前有过沟通，我们有采用过简繁互转工具来协助双方的翻译流程，同时我们也给laravel-tw 的 doc 提交过 PR，共同协作。

**Comment by artiship** [comment]
我也没有用个人账号啊，你说的这个没有问题，我想的只是做好翻译这件事情，而不是 close 这个 issue  @summerblue

**Comment by artiship** [comment]
你们缺乏开放的心态，试问照现在的情况，你们多长时间可以翻译出来文档 @summerblue
